const PRIMARYCOLOR = "#412a57";
const SECONDARYCOLOR = "#18c3d3";
const WHITECOLOR='white';

const HEADINGFONTFAMILY='PTSans';
const TITLEFONTFAMILY='calluna';


export { WHITECOLOR, PRIMARYCOLOR,HEADINGFONTFAMILY,TITLEFONTFAMILY,SECONDARYCOLOR }
